name: Continuous Integration

on:
  push:
  pull_request:
  schedule:
    - cron: '0 7 * * *'

jobs:
  test:
    strategy:
      matrix:
        java: [8, 11, 17]
        os: [ ubuntu-latest ]
    name: ${{ matrix.os }} / Java${{ matrix.java }}
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          check-latest: true
          distribution: 'temurin'
      - uses: coursier/cache-action@v6
      - name: install sbt
        run: curl -Ls https://git.io/sbt > ./sbt && chmod 0755 ./sbt
      - name: Run tests
        run: ./sbt test
